name: Sync wiki

on: [workflow_dispatch]

jobs:
  sync_wiki:
    runs-on: ubuntu-20.04
    steps:
      - name: Sync
        run: |
          git clone https://github.com/x64dbg/wiki wiki
          cd wiki
          git remote add wiki https://x64dbgbot:${{ secrets.WIKI_TOKEN }}@github.com/x64dbg/wiki.wiki.git
          git push --force wiki master
