name: Synchronize wiki

on: [ workflow_dispatch ]

jobs:
  sync_wiki:
    runs-on: ubuntu-latest
    steps:
      - name: Get wiki commit hash
        uses: jannekem/run-python-script-action@bbfca66c612a28f3eeca0ae40e1f810265e2ea68 # v1.7
        with:
          script: |
            import requests
            commit = requests.get("https://api.github.com/repos/x64dbg/wiki/commits/master", {"per_page": 1}).json()
            print(commit["sha"])
            set_env("WIKI_SHA", commit["sha"])

      - name: Set commit status as pending
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          status: pending
          repo: x64dbg/wiki
          sha: ${{ env.WIKI_SHA }}
          context: ${{ github.workflow }}

      - name: Synchronize wiki repository
        run: |
          git clone https://github.com/x64dbg/wiki wiki
          cd wiki
          git remote add wiki https://x64dbgbot:${{ secrets.WIKI_TOKEN }}@github.com/x64dbg/x64dbg.wiki.git
          git push --force wiki master

      - name: Set final commit status
        uses: myrotvorets/set-commit-status-action@3730c0a348a2ace3c110851bed53331bc6406e9f # v2.0.1
        if: ${{ always() }}
        with:
          token: ${{ secrets.WIKI_TOKEN }}
          status: ${{ job.status }}
          repo: x64dbg/wiki
          sha: ${{ env.WIKI_SHA }}
          context: ${{ github.workflow }}
